### ISSUE TITLE
Args object has no attribute 'cudas'

### ISSUE THREAD

**Issue by lleessang** [Glaciohound/VCML#3]
Hi, 

I am trying to replicate your project, but when running your sample single-experiment command, I am getting the cudas attribute not found error. Could you please give me some help? Thank you!

Traceback (most recent call last):
  File "scripts/main.py", line 38, in <module>
    main()
  File "scripts/main.py", line 28, in main
    run_experiment.run(args)
  File "/home/VCML/scripts/run_experiment.py", line 164, in run
    device = args.cudas[i * args.num_gpus // args.num_parallel]
AttributeError: 'Args' object has no attribute 'cudas'

> /home/VCML/scripts/run_experiment.py(164)run()
    162
    163     for i in range(0, args.num_parallel):
--> 164         device = args.cudas[i * args.num_gpus // args.num_parallel]
    165         p = ctx.Process(target=ready_go,
    166                         args=(args, i, message[i], control[i],

ipdb>

**Comment by lleessang** [comment]
I think I got the reason, it is because of torch.cuda.device_count() gives 0 while it needs to be greater than 0

**Comment by vacancy** [comment]
You should use a server with GPU installed. Closing.
