### ISSUE TITLE
Access forbidden to http://vcml.csail.mit.edu/data/ckpt/CLEVR_reason.tgz

### ISSUE THREAD

**Issue by anette123** [Glaciohound/VCML#4]
Hi team, have been trying to run your code using the example line:

`jac-crun <GPU-id> scripts/main.py --mode run-experiment --task CLEVR --model VCML --experiment synonym_generalization --num_parallel 1 --log_dir {log_dir} --data_dir {data_dir}`

But keep getting the error on: 

```
--2021-03-18 14:21:33--  http://vcml.csail.mit.edu/data/ckpt/CLEVR_reason.tgz
Resolving vcml.csail.mit.edu (vcml.csail.mit.edu)... 128.52.128.175
Connecting to vcml.csail.mit.edu (vcml.csail.mit.edu)|128.52.128.175|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-03-18 14:21:34 ERROR 403: Forbidden.
```

I also tried adding the option '--pretrained' to the same effect. Would you be able to help out? Looks like it is trying to load the file from some MIT data directory, which does not have general public access (I also tried access this file in the browser from my laptop [not from the cloud instance where I am running the code] and get the same response that it is forbidden.)

Thanks!

**Comment by vacancy** [comment]
Should be fixed now. Let me know if it still doesn't work.
