### ISSUE TITLE
How to generate synthetic questions and answers, based on the ground-truth annotations of visual concepts?

### ISSUE THREAD

**Issue by LemonQC** [Glaciohound/VCML#7]
The author said "We use programs to generate synthetic questions and answers, based on the ground-truth annotations of visual concepts", could you release the code.

**Comment by Glaciohound** [comment]
Thank you for your interests! `VCML/dataset/question_dataset/build_questions/build_questions.py` lists functions for constructing the questions and programs. Hope they can provide information that you are looking for.
